version: "3"

services:

  backend:
    build: .
    container_name: backend
    stdin_open: true
    tty: true
    volumes:
      - "./:/code/build"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MODE=runserver
    depends_on:
      - postgres
      - rabbitmq
      - memcached

  celery:
    build: .
    container_name: celery
    stdin_open: true
    tty: true
    volumes:
      - "./:/code/build"
    env_file:
      - .env
    environment:
      - MODE=celery
    depends_on:
      - postgres
      - rabbitmq
      - memcached

  celerybeat:
    build: .
    container_name: celerybeat
    stdin_open: true
    tty: true
    volumes:
      - "./:/code/build"
    env_file:
      - .env
    environment:
      - MODE=celerybeat
    depends_on:
      - rabbitmq

  memcached:
    image: memcached
    container_name: memcached
    env_file:
      - .env
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - backend

volumes:
  db_data: {}
